-- =========================================================================
--  Espace pédagogique STI — schéma de base de données (Supabase / PostgreSQL)
--  Prof. Aymen Essouyah — Lycée Rafèha Ariana — année 2026/2027
--
--  À exécuter une seule fois : Tableau de bord Supabase → « SQL Editor » →
--  coller ce script → « Run ».
-- =========================================================================

-- 1) Table des sauvegardes (instantanés de l'espace pédagogique) ------------
create table if not exists public.espace_pedagogique (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  prof         text,
  lycee        text,
  annee        text,
  device       text,                 -- « Téléphone », « Poste du lycée »…
  payload      jsonb not null        -- { times, seances, saved }
);

create index if not exists espace_pedagogique_created_at_idx
  on public.espace_pedagogique (created_at desc);

-- 2) Sécurité niveau ligne (RLS) ------------------------------------------
alter table public.espace_pedagogique enable row level security;

-- Lecture et écriture autorisées à la clé publique du projet.
-- ⚠️ Convenable pour un espace de travail personnel dont l'adresse n'est pas
-- publiée. Pour un dépôt public, remplacer les deux règles ci-dessous par la
-- variante « compte unique » donnée à la fin de ce fichier.
drop policy if exists "lecture espace" on public.espace_pedagogique;
drop policy if exists "ecriture espace" on public.espace_pedagogique;

create policy "lecture espace"
  on public.espace_pedagogique for select
  to anon
  using (true);

create policy "ecriture espace"
  on public.espace_pedagogique for insert
  to anon
  with check (true);

-- 3) Purge automatique (facultatif) ---------------------------------------
-- Conserver seulement les 200 derniers instantanés :
--   delete from public.espace_pedagogique
--   where id not in (select id from public.espace_pedagogique order by created_at desc limit 200);

-- 4) Variante « compte unique » (recommandée si le dépôt GitHub est public) -
-- Étape a : Authentication → Users → « Add user » (courriel + mot de passe).
-- Étape b : exécuter les instructions suivantes en remplaçant <UID> par
--           l'identifiant de l'utilisateur créé :
--
--   drop policy if exists "lecture espace" on public.espace_pedagogique;
--   drop policy if exists "ecriture espace" on public.espace_pedagogique;
--
--   create policy "lecture proprietaire"
--     on public.espace_pedagogique for select
--     to authenticated using (auth.uid() = '<UID>');
--
--   create policy "ecriture proprietaire"
--     on public.espace_pedagogique for insert
--     to authenticated with check (auth.uid() = '<UID>');
--
-- Le site devra alors être ouvert après connexion (Supabase Auth) : voir la
-- section « Sécuriser davantage » du README.md.
