-- =========================================================================
--  Espace pédagogique STI — base de sauvegarde (Supabase / PostgreSQL)
--  Multi-professeurs : chaque compte connecté possède SES sauvegardes.
--
--  À exécuter UNE SEULE FOIS : Supabase → SQL Editor → New query →
--  coller tout ce texte → Run. Aucune modification nécessaire.
--
--  Les comptes des professeurs sont créés par l'administrateur du projet :
--  Authentication → Users → Add user → Create new user
--  (adresse + mot de passe, cocher « Auto Confirm User »).
--  Les inscriptions restent fermées : Authentication → Sign In / Providers →
--  « Allow new users to sign up » : OFF.
-- =========================================================================

-- 1) Table des sauvegardes (instantanés de l'espace pédagogique) ------------
create table if not exists public.espace_pedagogique (
  id           bigint generated by default as identity primary key,
  created_at   timestamptz not null default now(),
  prof         text,                 -- nom du professeur (affiché)
  lycee        text,
  annee        text,
  device       text,                 -- « Téléphone », « Poste du lycée »…
  prof_id      uuid default auth.uid(),   -- propriétaire (compte connecté)
  payload      jsonb not null        -- { times, seances, profil, classes,
                                    --   eleves, epreuves, notes, presences }
);

create index if not exists espace_pedagogique_created_at_idx
  on public.espace_pedagogique (created_at desc);

-- 2) Sécurité : chaque professeur ne voit que SES sauvegardes --------------
alter table public.espace_pedagogique enable row level security;

drop policy if exists "lecture authentifiee"          on public.espace_pedagogique;
drop policy if exists "ecriture authentifiee"         on public.espace_pedagogique;
drop policy if exists "lecture proprietaire"          on public.espace_pedagogique;
drop policy if exists "ecriture proprietaire"         on public.espace_pedagogique;
drop policy if exists "lecture espace"                on public.espace_pedagogique;
drop policy if exists "ecriture espace"               on public.espace_pedagogique;
drop policy if exists "lecture espace (propre prof)"  on public.espace_pedagogique;
drop policy if exists "ecriture espace (propre prof)" on public.espace_pedagogique;

create policy "lecture espace (propre prof)"
  on public.espace_pedagogique for select
  to authenticated
  using (prof_id = auth.uid());

create policy "ecriture espace (propre prof)"
  on public.espace_pedagogique for insert
  to authenticated
  with check (prof_id = auth.uid());

-- Sans connexion, la table est totalement inaccessible.

-- 3) (Facultatif) Purge ----------------------------------------------------
-- Conserver seulement les 200 derniers instantanés :
--   delete from public.espace_pedagogique
--   where id not in (select id from public.espace_pedagogique order by created_at desc limit 200);
